from __future__ import annotations

import hashlib
import stat
from dataclasses import dataclass
from pathlib import Path

from .paths import is_below
from .trees import TreeError, read_regular_file


class ComposeError(Exception):
    pass


@dataclass(frozen=True)
class Composition:
    """A generated file and the exact source bytes it was built from."""

    output: str
    body: str
    source_hashes: dict[str, str]


def marker(sources: tuple[str, ...]) -> str:
    return (
        f"<!-- Generated by ai-config from {', '.join(sources)}. "
        "Do not edit this file; edit the sources and run ai-config install. -->"
    )


def read_sources(repo_root: Path, sources: tuple[str, ...]) -> dict[str, bytes]:
    """Read each source once; each must be a regular, non-link file that resolves inside the repository."""
    repo_root = repo_root.resolve()
    data = {}
    for source in sources:
        path = repo_root / source
        try:
            info = path.lstat()
            if not stat.S_ISREG(info.st_mode):
                raise ComposeError(f"compose source is not a regular file: {source}")
            if not is_below(path.resolve(), repo_root):
                raise ComposeError(f"compose source resolves outside the repository: {source}")
            data[source] = read_regular_file(path)[0]
        except FileNotFoundError:
            raise ComposeError(f"compose source does not exist: {source}")
        except OSError as error:
            raise ComposeError(f"cannot read compose source {source}: {error.strerror or error}")
        except TreeError as error:
            raise ComposeError(f"cannot read compose source {source}: {error}")
    return data


def compose(repo_root: Path, sources: tuple[str, ...]) -> Composition:
    """Join the sources with one blank line between them, below a marker naming them.

    Leading and trailing blank lines of each source are dropped, and empty sources are skipped.
    """
    data = read_sources(repo_root, sources)
    parts = []
    for source in sources:
        try:
            text = data[source].decode("utf-8")
        except UnicodeDecodeError:
            raise ComposeError(f"compose source is not UTF-8: {source}")
        if text.strip():
            parts.append(text.strip("\n"))
    body = "\n\n".join(parts) + "\n" if parts else ""
    hashes = {source: hashlib.sha256(content).hexdigest() for source, content in data.items()}
    return Composition(f"{marker(sources)}\n\n{body}", body, hashes)


def text_hash(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def current_source_hashes(repo_root: Path, sources: tuple[str, ...]) -> dict[str, str]:
    return {source: hashlib.sha256(content).hexdigest() for source, content in read_sources(repo_root, sources).items()}
